In [ ]:
# 1. How to Creating a 3x3 Identity Matrix with Float Data Type?

import numpy as np

array1 = np.eye(3,3,dtype=float)
array1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 2. Create a 1D Array with Random Values between 0 and 1.

array = np.random.rand(10)
array


array([0.77057342, 0.56302505, 0.6746735 , 0.84803165, 0.12747612,
       0.763635  , 0.40968029, 0.83983016, 0.93397349, 0.54008658])

In [ ]:
# 3. Create a 2D Array with Random Integer Values.

array2 = np.random.randint(1,10,size=(2,2))
array2



array([[5, 2],
       [6, 2]])

In [ ]:
# 4. Creating an Array Using a Custom Function.


# ---------  Custom Function  ---------
"""def cube(y):
    return y * y * y

arr1 = np.array([cube(i) for i in range(1, 6)])
arr1"""


def square(x):
    return x * x

arr = np.array([square(i) for i in range(1, 6)])
arr




array([ 1,  4,  9, 16, 25])

In [ ]:
# 5. Reshaping a 1D Array into a 2D Array

arr1 = [10,12,13,14]

arr2 = np.reshape(arr1,(2,2))
arr2


array([[10, 12],
       [13, 14]])

In [ ]:
# 6.How to Creating a 3x3 Array of Ones?

array_3d = np.ones((3,3),dtype=int)
array_3d

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# 7. How to get the common items between two pythons NumPy?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

common_items = np.intersect1d(a,b)
common_items

array([2, 4])

In [ ]:
#  8. From array a remove all items present in array b Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

remove_all = np.setdiff1d(a,b)
remove_all


array([1, 2, 3, 4])

In [ ]:
# 9. Limit the number of items printed in python NumPy array a to a maximum of 6 elements.

a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
# 10. Drop all nan values from a 1D NumPy array Input:

a = np.array([1,2,3, np.nan,5,6,7, np.nan])

drop_all = a[~np.isnan(a)]
print(drop_all)

[1. 2. 3. 5. 6. 7.]


In [ ]:
# 11. Question: Create a 1D NumPy array of the first 20 natural numbers and a 2D NumPy array of shape (4, 5) with values ranging from 1 to 20.

arr1 = np.arange(1,21)
arr2 = np.arange(1,21,).reshape(4,5)
print(f"1D NumPy array : ",arr1)
print(f"2D NumPy array : ",arr2)

1D NumPy array :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2D NumPy array :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
# 12. Question: Given a 3D NumPy array of shape (2, 3, 4), find its shape, size, number of dimensions, and data type. Change its data type to float64 and verify the change.

arr3 = np.arange(24).reshape(2,3,4)
print(f"3D NumPy array : ",arr3)

print("Shape:", arr3.shape)
print("Size:", arr3.size)
print("Number of dimensions:", arr3.ndim)
print("Data type:", arr3.dtype)

arr_float = arr.astype(np.float64)
print("New data type:", arr_float.dtype)

3D NumPy array :  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape: (2, 3, 4)
Size: 24
Number of dimensions: 3
Data type: int64
New data type: float64
3D NumPy array :  [ 1.  4.  9. 16. 25.]


In [ ]:
# 13. Question: Reshape a 1D array of 12 elements into a 3x4 2D array and then flatten it back into a 1D array using ravel (). Verify that the flattened array matches the original.

arr1d = np.arange(1,13)
arr1d
arr2d = arr1d.reshape(3,4)
arr2d

flattened = arr2d.ravel()

print("Original 1D array:", arr1d)
print("Reshaped 2D array:\n", arr2d)
print("Flattened array:", flattened)

print("Arrays match:", np.array_equal(arr1d, flattened))

Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Arrays match: True


In [ ]:
# 14. Question: Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4, 5, 6]), performelement-wise addition, subtraction, multiplication, and division. Explain the behavior when dividing by zero.

a = np. array([1, 2, 3])
b = np. array([4, 5, 6])

add = a + b
sub = a - b
mul = a * b
div = a / b
print(" ", " ")
print(f"addition     :-",add)
print(f"substraction    :-",sub)
print(f"multiplication   :-",mul)
print(f"division   :-",div)


   
addition     :- [5 7 9]
substraction    :- [-3 -3 -3]
multiplication   :- [ 4 10 18]
division   :- [0.25 0.4  0.5 ]


In [ ]:
# 15. Question: Create a 2D array of shape (3, 1) and a 1D array of length 3. Perform element-wise addition using broadcasting. Explain how broadcasting rules apply in this scenario.

"""NumPy compares shapes from right to left.
If dimensions are equal or one of them is 1, broadcasting is possible.
Dimension with size 1 is expanded to match the other."""

import numpy as np

a = np.array([[1],[2],[3]])
b = np.array([10,20,30])

c = a + b
print(c)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
# 16. Question: Generate a random 2D array of integers between 0 and 10. Use  conditional operators to create a Boolean mask identifying elements greater than 5. Replace all elements greater than 5 with the value 5.

array_2d = np.random.randint(0,11, size = (3,3))

mask = array_2d > 5
print("Boolean mask identifying elements greater than 5",mask)

array_2d[array_2d > 5] = 5
print("Modified Array:\n", array_2d)
array_2d

Boolean mask identifying elements greater than 5 [[False False False]
 [False False False]
 [ True False  True]]
Modified Array:
 [[4 1 4]
 [4 0 3]
 [5 5 5]]


array([[4, 1, 4],
       [4, 0, 3],
       [5, 5, 5]])

In [ ]:
# 17. Question: Given a 4x4 array of random integers, use indexing and slicing to extract:
"""The entire second row
The last column
The subarray consisting of the first two rows and first two columns"""

array = np.random.randint(0,50, size = (4,4))
print("Original Array:\n", array)
print(f"The entire second row ",array[1,:])
print(f"The last column",array[:,3])
print(f"The subarray consisting of the first two rows and first two columns",array[0:2,0:2])

Original Array:
 [[10 24 42  3]
 [31 16 42 11]
 [26 25 18 12]
 [ 2  7 32 40]]
The entire second row  [31 16 42 11]
The last column [ 3 11 12 40]
The subarray consisting of the first two rows and first two columns [[10 24]
 [31 16]]


In [ ]:
# 18. Question: Describe a practical example where NumPy can be used in EDA, AI, ML, and DL, and implement a NumPy solution for a simple task in each area.
"""
NumPy provides fast numerical operations and efficient array handling, making it essential for EDA, AI, ML, and Deep Learning.
It forms the backbone of data processing and mathematical computation in modern data science."""

#1.EDA (Exploratory Data Analysis)
print("--------- EDA (Exploratory Data Analysis)------------")
sales = np.array([1200, 1500, 1800, 900, 2000])

print("Mean Sales:", np.mean(sales))
print("Maximum Sales:", np.max(sales))
print("Minimum Sales:", np.min(sales))

#2.AI (Artificial Intelligence)
print("--------- AI (Artificial Intelligence)------------")
scores = np.array([80, 45, 90, 60])
decision = scores > 60

print("Decision Result:", decision)

#3.ML (Machine Learning)
print("--------- ML (Machine Learning)------------")
x = np.array([1, 2, 3, 4])
y = np.array([2, 4, 6, 8])

m = 2
y_pred = m * x

print("Predicted Values:", y_pred)

#4.DL (Deep Learning)
print("--------- DL (Deep Learning)------------")
inputs = np.array([1.0, 0.5, 0.2])
weights = np.array([0.4, 0.6, 0.8])

output = np.dot(inputs, weights)
print("Neuron Output:", output)

--------- EDA (Exploratory Data Analysis)------------
Mean Sales: 1480.0
Maximum Sales: 2000
Minimum Sales: 900
--------- AI (Artificial Intelligence)------------
Decision Result: [ True False  True False]
--------- ML (Machine Learning)------------
Predicted Values: [2 4 6 8]
--------- DL (Deep Learning)------------
Neuron Output: 0.86


In [ ]:
# 19. Question: Create a random 4x4 matrix and use NumPy to compute its eigenvalues and eigenvectors. Verify the eigenvalues by reconstructing the matrix.

array = np.random.randint(0,50, size = (4,4))
print("Original Array:\n", array)

eigenvalues, eigenvectors = np.linalg.eig(array)

print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

D = np.diag(eigenvalues)

array_reconstructed = eigenvectors @ D @ np.linalg.inv(eigenvectors)

print("\nReconstructed Matrix:\n", array_reconstructed)
print("\nVerification Result:", np.allclose(array, array_reconstructed))

Original Array:
 [[37 41 42 13]
 [37 17 38 35]
 [18 17 27 15]
 [28  9 49 48]]

Eigenvalues:
 [113.42300363  21.37905245  -5.92810886   0.12605278]

Eigenvectors:
 [[ 0.55593098  0.6615561   0.55904392 -0.30565826]
 [ 0.53753766 -0.05380458 -0.69921481  0.59350286]
 [ 0.31684462  0.03769096  0.2294131  -0.48568416]
 [ 0.5491844  -0.74701271 -0.38201856  0.56430336]]

Reconstructed Matrix:
 [[37. 41. 42. 13.]
 [37. 17. 38. 35.]
 [18. 17. 27. 15.]
 [28.  9. 49. 48.]]

Verification Result: True


In [ ]:
# 20. Question: Create a 1D array of 27 elements and reshape it into a 3x3x3 3D array. Flatten it back into a 1D array and compare the flattened array with the original.

arr1d = np.arange(1,28)
arr1d
arr2d = arr1d.reshape(3,3,3)
arr2d

flattened = arr2d.flatten()

print("Original 1D array:", arr1d)
print("Reshaped 2D array:\n", arr2d)
print("Flattened array:", flattened)

print("Arrays match:", np.array_equal(arr1d, flattened))

Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
Reshaped 2D array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
Arrays match: True


In [ ]:
# 21. Question: Perform matrix multiplication of two 2D arrays using np.dot () and @. Compare the results and performance of both methods using a large dataset.
import time

A = np.random.rand(1000, 1000)
B = np.random.rand(1000, 1000)
print("A: ",A)
print("B: ",B)


start = time.time()
matrix_multiplication = np.dot(A,B)
end = time.time()
print("Time taken using np.dot():", end - start)

start = time.time()
result_at = A @ B
end = time.time()
print("Time taken using @ operator:", end - start)

print("Results are equal:", np.allclose(matrix_multiplication, result_at))

A:  [[5.25888325e-01 2.37674788e-02 9.29518510e-02 ... 1.95410372e-01
  1.70392694e-04 4.10104641e-01]
 [3.32837812e-01 2.21359268e-01 5.04802391e-01 ... 3.12464260e-01
  6.64891793e-01 8.92755381e-01]
 [5.61618399e-01 5.40785626e-01 8.11421006e-01 ... 2.03711150e-01
  2.42443790e-01 1.13321256e-01]
 ...
 [5.67798644e-01 3.48318976e-01 8.48806170e-02 ... 8.72621768e-01
  4.38303013e-01 8.49562889e-01]
 [8.30100947e-02 7.54780428e-01 8.63564314e-01 ... 6.63979651e-01
  5.74996058e-01 7.78547778e-01]
 [9.87917029e-01 9.94497618e-01 4.03031830e-01 ... 3.07705895e-01
  5.27077253e-01 7.73096616e-01]]
B:  [[0.8481434  0.36265096 0.25871755 ... 0.69346875 0.67820982 0.86807796]
 [0.69083842 0.20342773 0.33037252 ... 0.92367969 0.10032715 0.82160629]
 [0.98201956 0.21110739 0.33832346 ... 0.79665231 0.5940679  0.8374644 ]
 ...
 [0.36203056 0.41994304 0.75044684 ... 0.01098364 0.23720853 0.16626017]
 [0.66942435 0.04046389 0.19289807 ... 0.60906508 0.21914441 0.69870816]
 [0.01262341 0.7379263

In [ ]:
# 22. Question: Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4, 1). Perform an element-wise operation using broadcasting and explain the result. Use np. new axis to achieve the same result without broadcasting.

A = np.array([[[1, 2, 3, 4]],
              [[5, 6, 7, 8]]])
B = np.array([[10],
              [20],
              [30],
              [40]])
print("Shape of A:", A.shape)
print("Shape of B:", B.shape)

result_broadcast = A + B
print("\nResult using broadcasting:\n", result_broadcast)
print("Result shape:", result_broadcast.shape)

B_new = B[np.newaxis, :, :]

print("Shape of B after newaxis:", B_new.shape)

result_newaxis = A + B_new
print("\nResult using np.newaxis:\n", result_newaxis)

print("\nResults are equal:",
      np.array_equal(result_broadcast, result_newaxis))

Shape of A: (2, 1, 4)
Shape of B: (4, 1)

Result using broadcasting:
 [[[11 12 13 14]
  [21 22 23 24]
  [31 32 33 34]
  [41 42 43 44]]

 [[15 16 17 18]
  [25 26 27 28]
  [35 36 37 38]
  [45 46 47 48]]]
Result shape: (2, 4, 4)
Shape of B after newaxis: (1, 4, 1)

Result using np.newaxis:
 [[[11 12 13 14]
  [21 22 23 24]
  [31 32 33 34]
  [41 42 43 44]]

 [[15 16 17 18]
  [25 26 27 28]
  [35 36 37 38]
  [45 46 47 48]]]

Results are equal: True


In [ ]:
# 23. Question: Generate a 2D array of random floats between 0 and 1. Use conditional operators to create a Boolean mask for values less than 0.5. Replace these values with their squares and leave the rest unchanged.

A = np.random.rand(4,4)
print("Original Array:\n", A)


mask = A < 0.5
print("Boolean mask identifying elements Less than 0.5",mask)

A_modifi = A.copy()
A_modifi[mask] = A_modifi[mask] ** 2

print("\nModified Array:\n", A_modifi)

Original Array:
 [[0.44756735 0.00678856 0.10326092 0.30792384]
 [0.83018846 0.44643063 0.12259336 0.65715309]
 [0.99343119 0.57500311 0.46146347 0.92776202]
 [0.07473705 0.03283131 0.41629436 0.74234285]]
Boolean mask identifying elements Less than 0.5 [[ True  True  True  True]
 [False  True  True False]
 [False False  True False]
 [ True  True  True False]]

Modified Array:
 [[2.00316534e-01 4.60845340e-05 1.06628166e-02 9.48170900e-02]
 [8.30188462e-01 1.99300307e-01 1.50291315e-02 6.57153094e-01]
 [9.93431189e-01 5.75003107e-01 2.12948535e-01 9.27762024e-01]
 [5.58562711e-03 1.07789476e-03 1.73300990e-01 7.42342845e-01]]


In [ ]:
# 24. Question: Given a 5x5 array of sequential integers, use slicing to:
"""Extract the diagonal elements
Replace the elements of the middle row with zeros
Flip the array vertically and horizontally """

A = np.arange(1,26).reshape(5,5)
print(A)

diagonal_elements = np.diag(A)
print("\n diagonal elements: ", diagonal_elements)

A[2, :] = 0
print("\n middle row: ", A)

vertical_flip = A[::-1, :]
print("\nVertically Flipped Array:\n", vertical_flip)

horizontal_flip = A[:, ::-1]
print("\nHorizontally Flipped Array:\n", horizontal_flip)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

 diagonal elements:  [ 1  7 13 19 25]

 middle row:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 0  0  0  0  0]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Vertically Flipped Array:
 [[21 22 23 24 25]
 [16 17 18 19 20]
 [ 0  0  0  0  0]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]

Horizontally Flipped Array:
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [ 0  0  0  0  0]
 [20 19 18 17 16]
 [25 24 23 22 21]]


In [ ]:
# 25. Question: Create a 4D array of shape (2, 3, 4, 5) with random integers. Use advanced slicing to extract a subarray and compute the mean along a specified axis.

A = np.random.randint(1,100,size=(2,3,4,5))
print(A)
print(A.shape)

sub_arr = A[1, 0:2, :, 0:3]
print("Shape of subarray:", sub_arr.shape)

mean_result = np.mean(sub_arr, axis=1)
print("Mean along axis 1:\n", mean_result)

[[[[75 79 93  2 35]
   [28 87  1  8 67]
   [31 92 32 14 74]
   [ 7 42 56 76 94]]

  [[97 65 80 88 99]
   [77 15 79 81 76]
   [77 34 46 83 23]
   [73 91 50 68  4]]

  [[71 54 40  7 10]
   [63 32 49 73 96]
   [14 90 13 31 18]
   [99 56 43 43 17]]]


 [[[34 88  1 18 99]
   [93 14 75 79 92]
   [16 54  4 34 21]
   [ 8 36 57 32 58]]

  [[28 14 96 76 22]
   [98  9 81 57 21]
   [71 77 15 40 34]
   [51 78 23 72 12]]

  [[73  9 58 99 96]
   [64 51 49 76 55]
   [93 34  3 66 38]
   [41 73  3 58 67]]]]
(2, 3, 4, 5)
Shape of subarray: (2, 4, 3)
Mean along axis 1:
 [[37.75 48.   34.25]
 [62.   44.5  53.75]]


In [ ]:
# 26. Question: Given an array of shape (10, 20), reshape it to (20, 10) and (5, 40). Discuss the impact on the array's shape, size, and dimensionality.

A = np.arange(200).reshape(10,20)
print(A)
print("Original array:",A.shape)

A_20_10 = A.reshape(20,10)
print("\n reshape A :", A_20_10)

A_5_40 = A.reshape(5,40)
print("\n reshape A :", A_5_40)

"""array's shape - Original shape: (10, 20)
After reshaping: (20, 10) and (5, 40)
Shape changes based on how elements are arranged in rows and columns"""

"""size - Total elements remain the same:
10 × 20 = 20 × 10 = 5 × 40 = 200
Reshaping is allowed only when total size is unchanged"""

"""Dimensionality - Original array: 2D
Reshaped arrays: still 2D
Number of dimensions does not change, only layout does"""

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
  178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
  198 199]]
Original array: (10, 20)

 reshape A : [[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  2

'Dimensionality - Original array: 2D\nReshaped arrays: still 2D\nNumber of dimensions does not change, only layout does'

In [ ]:
# 27. Question: Generate a large 2D array and demonstrate the use of np. reshape () and unravel () to manipulate its shape for various linear algebra operations.

"""reshape() and ravel() allow flexible manipulation of array shapes, making NumPy efficient for large-scale linear algebra computations.
"""
A = np.random.rand(1000, 1000)
print("Original shape:", A.shape)

A_vector = A.reshape(-1)
print("Reshaped to 1D vector:", A_vector.shape)

A_reshaped = A.reshape(500, 2000)
print("Reshaped matrix shape:", A_reshaped.shape)

A_flat = A.ravel()
print("Flattened array shape:", A_flat.shape)

dot_result = np.dot(A_flat, A_flat)
print("Dot product result:", dot_result)

Original shape: (1000, 1000)
Reshaped to 1D vector: (1000000,)
Reshaped matrix shape: (500, 2000)
Flattened array shape: (1000000,)
Dot product result: 332848.6540881442


In [ ]:
# 28. Question: Given a 6x6 matrix, use advanced indexing and slicing to extract the upper triangular part of the matrix and set the lower triangular part to zero. Verify the result.

A = np.arange(1, 37).reshape(6, 6)
print("Original Matrix:\n", A)

upper_tri = A.copy()

lower_indices = np.tril_indices(6, k=-1)

upper_tri[lower_indices] = 0

print("\nUpper Triangular Matrix:\n", upper_tri)

is_lower_zero = np.all(upper_tri[np.tril_indices(6, k=-1)] == 0)
print("\nVerification (Lower triangular zero?):", is_lower_zero)

Original Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Upper Triangular Matrix:
 [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]

Verification (Lower triangular zero?): True
